# Generated by Django 5.2.5 on 2025-11-08 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_user_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('view_student', 'View Student'), ('add_student', 'Add Student'), ('change_student', 'Change Student'), ('delete_student', 'Delete Student'), ('view_teacher', 'View Teacher'), ('add_teacher', 'Add Teacher'), ('change_teacher', 'Change Teacher'), ('delete_teacher', 'Delete Teacher'), ('view_class', 'View Class'), ('add_class', 'Add Class'), ('change_class', 'Change Class'), ('delete_class', 'Delete Class'), ('view_subject', 'View Subject'), ('add_subject', 'Add Subject'), ('change_subject', 'Change Subject'), ('delete_subject', 'Delete Subject'), ('view_grade', 'View Grade'), ('add_grade', 'Add Grade'), ('change_grade', 'Change Grade'), ('delete_grade', 'Delete Grade'), ('view_payment', 'View Payment'), ('add_payment', 'Add Payment'), ('change_payment', 'Change Payment'), ('delete_payment', 'Delete Payment'), ('view_schedule', 'View Schedule'), ('add_schedule', 'Add Schedule'), ('change_schedule', 'Change Schedule'), ('delete_schedule', 'Delete Schedule'), ('view_user', 'View User'), ('add_user', 'Add User'), ('change_user', 'Change User'), ('delete_user', 'Delete User'), ('view_audit_log', 'View Audit Log')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='university.permission'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(related_name='roles', to='university.permission')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='university.role'),
        ),
    ]
