# Generated by Django 5.2.5 on 2025-11-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_payment_description_payment_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('Exam', 'Exam'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Project', 'Project'), ('Other', 'Other')], default='Exam', max_length=20)),
                ('weight', models.FloatField(help_text='Weight in percentage (e.g., 50 for 50%)')),
                ('date', models.DateField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='university.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='university.subject')),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.assessment'),
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('final_grade_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('final_score', models.FloatField()),
                ('final_grade', models.CharField(max_length=2)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='university.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='university.subject')),
            ],
            options={
                'db_table': 'final_grades',
                'unique_together': {('student', 'subject', 'semester', 'year')},
            },
        ),
    ]
