# Generated by Django 5.2.5 on 2025-11-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_assessment_grade_assessment_finalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='university.assessment'),
        ),
    ]
