# Generated by Django 5.2.5 on 2025-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pictures/'),
        ),
    ]
